name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.1.0
        with:
          source_dir: ./src
          output_dir: ./out
          config_file: conf.json
          template_name:
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
